### ISSUE TITLE
Error Running scripts/amazon_clothing_20k/eval_rank.sh : Leaf Variable in In-Place Operation

### ISSUE THREAD

**Issue by William3242** [twelfth-star/LinkGPT#4]
I encountered an issue while running the eval_rank.sh script in the amazon_clothing_20k directory. The error occurs when executing the Python script as part of the evaluation process. Here is the detailed traceback:

```
Traceback (most recent call last):
  File "/home/wlhuang/llm/LinkGPT/linkgpt/eval/eval_yn.py", line 311, in <module>
    main()
  File "/home/wlhuang/llm/LinkGPT/linkgpt/eval/eval_yn.py", line 131, in main
    model, tokenizer = load_model_and_tokenizer(
  File "/home/wlhuang/llm/LinkGPT/linkgpt/model/linkgpt_model.py", line 479, in load_model_and_tokenizer
    ft_model.base_model.model.model.embed_tokens.weight[linkgpt_special_token_id_ls] = linkgpt_special_token_emb
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```

It seems like the issue is related to an in-place assignment on a leaf variable that requires gradients, which is causing the error. I have tried wrapping the assignment in `torch.no_grad() `to prevent the calculation graph from being modified, but I would like to know if there is a more appropriate solution for this particular scenario.

Environment details:

```
Python version: 3.9

PyTorch version: 1.13.1

CUDA version: 11.7

Transformers library version: 4.41.2

DGL version: 2.0.0+cu116

```
Could you please provide guidance on how to properly address this error? Any help would be much appreciated.

**Comment by twelfth-star** [comment]
Thank you very much for raising this issue! I encountered the same problem during my testing. I suspect the reason I didn’t encounter this issue earlier might be due to some version discrepancies in the libraries. I’m not sure if there’s a more elegant solution, so I resolved it using the `torch.no_grad()` method as you suggested. The code in `LinkGPT/linkgpt/model/linkgpt_model.py` has been updated accordingly.
